## Todo List
* Evaluation Metric ***(Precision, Recall, Accuracy, F1 score)***
* Standardize data samples ***(Sklearn)***
* Variable learning rate ***(PyTorch)***
* Graph font size ***(Matplotlib)***
* ~~Intra-iteration ***(IFI-RNN)***~~
* Early stop ***(PyTorch)***
* About convergence ***(Google)***
* StratifiedKFold ***(Sklearn)***
* Sliding windows
* Continuous action data test

In [27]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [15]:
def intra_iteration(x, iter_num=2):
    y = []
    for i in range(len(x)):
        y.append(x[i][[i//iter_num for i in range(iter_num*x[i].shape[0])],:])
    
    return np.array(y)

In [20]:
a = [[1,2,3], [4,5,6]]
t = [a, a, a]
t = np.array(t)
t[1] += 1
print(t)`
t = np.array(t)
print(t)
t = intra_iteration(t)
print(t)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]

 [[2 3 4]
  [2 3 4]
  [5 6 7]
  [5 6 7]]

 [[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]]


In [29]:
np.mean([1,2,3,4,5])

3.0